version: '3.8'

services:
  app:
    build: .
    container_name: gocalis-app
    volumes:
      - .:/app
      - /dev/snd:/dev/snd
    network_mode: host
    privileged: true
    environment:
      - ALSADEV=default
    command: tail -f /dev/null
