// Run in the pinned Playwright container; no dependency enters the application.
const { chromium } = require('playwright');
const assert = require('node:assert/strict');
(async () => {
  const browser = await chromium.launch({ args: ['--use-fake-ui-for-media-stream', '--use-fake-device-for-media-stream'] });
  const context = await browser.newContext({ permissions: ['microphone'] });
  const page = await context.newPage();
  const errors = []; page.on('pageerror', error => errors.push(error.message));
  await page.goto(process.env.SIMULATOR_URL || 'http://127.0.0.1:18080');
  await page.locator('article').nth(2).waitFor();
  assert.equal(await page.locator('article').count(), 3);
  const kitchen = page.locator('article').filter({ has: page.getByRole('heading', { name: 'kitchen', exact: true }) });
  await kitchen.locator('input').setInputFiles({ name: 'bad.wav', mimeType: 'audio/wav', buffer: Buffer.from('bad') });
  await kitchen.getByRole('button', { name: 'Replay WAV' }).click();
  await page.getByRole('status').filter({ hasText: 'expected PCM16' }).waitFor();
  const buffer = Buffer.alloc(44 + 16000); buffer.write('RIFF'); buffer.writeUInt32LE(buffer.length - 8, 4); buffer.write('WAVEfmt ', 8); buffer.writeUInt32LE(16, 16); buffer.writeUInt16LE(1, 20); buffer.writeUInt16LE(1, 22); buffer.writeUInt32LE(16000, 24); buffer.writeUInt32LE(32000, 28); buffer.writeUInt16LE(2, 32); buffer.writeUInt16LE(16, 34); buffer.write('data', 36); buffer.writeUInt32LE(16000, 40);
  for (let i = 0; i < 8000; i++) buffer.writeInt16LE(Math.round(10000 * Math.sin(2 * Math.PI * 600 * i / 16000)), 44 + i * 2);
  await kitchen.locator('input').setInputFiles({ name: 'tone.wav', mimeType: 'audio/wav', buffer });
  await kitchen.getByRole('button', { name: 'Replay WAV' }).click();
  await page.getByRole('status').filter({ hasText: 'Playing tone.wav' }).waitFor();
  await kitchen.getByRole('button', { name: 'Stop input', exact: true }).click();
  await kitchen.getByRole('button', { name: 'Use browser mic' }).click();
  await page.getByRole('status').filter({ hasText: 'Browser microphone → kitchen' }).waitFor();
  await page.waitForFunction(async () => (await (await fetch('/api/devices')).json()).find(d => d.id === 'kitchen').input === 'live');
  await kitchen.getByRole('button', { name: 'Replay WAV' }).click();
  await page.getByRole('status').filter({ hasText: 'live microphone owns' }).waitFor();
  await kitchen.getByRole('button', { name: 'Stop input', exact: true }).click();
  await page.waitForFunction(async () => (await (await fetch('/api/devices')).json()).find(d => d.id === 'kitchen').input === 'silence');
  await kitchen.getByRole('button', { name: 'Disconnect', exact: true }).click();
  await kitchen.locator('small').filter({ hasText: 'offline' }).waitFor();
  await kitchen.getByRole('button', { name: 'Reconnect', exact: true }).click();
  await kitchen.locator('small').filter({ hasText: 'online' }).waitFor();
  await page.getByRole('button', { name: 'Run scenario', exact: true }).click();
  await page.locator('#report').filter({ hasText: '"passed": true' }).waitFor();
  const response = await page.request.get('http://127.0.0.1:18080/api/devices/kitchen/recording');
  assert.equal(response.headers()['content-type'], 'audio/wav');
  assert.equal((await response.body()).subarray(0, 4).toString(), 'RIFF');
  let outstanding = 0, maximum = 0;
  await page.route('**/api/devices', async route => {
    outstanding++; maximum = Math.max(maximum, outstanding);
    await new Promise(resolve => setTimeout(resolve, 800));
    await route.continue(); outstanding--;
  });
  await page.waitForTimeout(2200);
  assert.equal(maximum, 1, 'slow UI polling must remain bounded');
  assert.deepEqual(errors, []);
  await browser.close();
  console.log('Browser checks passed: upload, live AudioWorklet, exclusive inputs, connection controls, scenario, recording.');
})().catch(error => { console.error(error); process.exit(1); });
